### ISSUE TITLE
Outgoing message height is not increasing 

### ISSUE THREAD

**Issue by veersr9** [sendbird/SendBird-iOS#63]
If I am trying to increase outgoing message height it is not increasing.

**Comment by AlexPrestonSB** [comment]
Hey @veersr9, 

Could you provide a little more context for your problem so I can help you out, thanks!

**Comment by veersr9** [comment]
Hello @AlexPrestonSB  
     When I am sending message to another user and printing the full message . Then I am counting characters of messages it's 100 character .


"

let cellHeight = self.dateContainerTopMargin.constant + self.dateContainerHeight.constant + self.dateContainerBottomMargin.constant + self.messageContainerTopPadding.constant + fullMessageSize.height + self.messageContainerBottomPadding.constant

"

**Comment by AlexPrestonSB** [comment]
Let me see if I understand, you are wanting to figure out dynamically how to display your recently sent message?
