### ISSUE TITLE
Delete specific message

### ISSUE THREAD

**Issue by veersr9** [sendbird/SendBird-iOS#66]
I am deleting particular message from chat . And I am passing "var message = SBDBaseMessage!" but it is not going inside completion handle . Why? and Why it is not working ?

I am using your code as it is.

self.groupChannel?.delete(message, completionHandler: { (error) in
            guard error == nil else {       // Error.
                return
            }
        })

**Comment by AlexPrestonSB** [comment]
Hey @veersr9 

I think you used the guard statement wrong. Can you try this?

```swift
guard error {
  // Fill in handler
}
```
Also for future issues could you submit a ticket via Zendesk as we are quicker to respond to those, and we can keep better track of those. Thank you!
