### ISSUE TITLE
I am getting groupChannels nil. While I am sending two users channel id.

### ISSUE THREAD

**Issue by veersr9** [sendbird/SendBird-iOS#69]
let query = SBDGroupChannel.createMyGroupChannelListQuery()
        query?.setUserIdsExactFilter(["\(myId!), \(otherUserId)"])
        query?.loadNextPage(completionHandler: { (groupChannels, error) in
            // Only 'channelA' is returned.
            print(groupChannels)
        })

**Comment by erickimme** [comment]
Hello @veersr9, 

Thank you for your interest in SendBird's messaging/chat API and we appreciate your time to ask inquiries.

To help you better, can you submit a support ticket via [SendBird dashboard](https://dashboard.sendbird.com/)dashboard>support>contact>technical?
