### ISSUE TITLE
Fetching messages is not calling the completion handler

### ISSUE THREAD

**Issue by biolattof** [sendbird/SendBird-iOS#73]
When calling the fetch function, it seems to works but sometimes the completion handler never gets called and from that time, every subsequent call to fetch won't call the completion handler either. I setted my delegate and my collection is not nil.

**Comment by AlexPrestonSB** [comment]
Hey @biolattof we are looking into this, and working on a solution. Thank you!

**Comment by harryraturi** [comment]
Hey @AlexPrestonSB , this is not working for me as well, can you please give me an ETA on when the fix will be out.

**Comment by AlexPrestonSB** [comment]
@harryraturi @biolattof, this should be resolved on the latest release.
