### ISSUE TITLE
Streamline sample chat ApplicationId across all samples.

### ISSUE THREAD

**Issue by SamQuest** [sendbird/SendBird-iOS#82]
I logged in to [sample](https://sample.sendbird.com/basic/)
Then installed sample [SendBird-Android](https://github.com/sendbird/SendBird-Android/tree/master/syncmanager) 
Then installed [SendBird-iOS](https://github.com/sendbird/SendBird-iOS/tree/master/syncmanager/swift)

Android and Web samples can send message to each other. 
Was not able to send messages from iOS sample.

Took some time to dawn on me
Please change the **ApplicationId** so future users will not stumble here.
I ended up copying the ApplicationId from the Android Sample to continue the evaluation process.

**Comment by BC-Chung** [comment]
Hello

Sorry for the confusion.
We found that our iOS SyncManager sample is using another Application ID unlike other samples.
We will change the Application ID and release new version.
Thanks!

Best regards
BC Chung
Solutions Engineer 
SendBird

**Comment by BC-Chung** [comment]
Hello

New version of iOS SyncManager sample(v3.0.93) has been release.
Will close this ticket.
Thanks!

Best regards
BC Chung
Solutions Engineer
SendBird
